import 'zx/globals'

import { writeFileSync } from 'node:fs'
import { Command } from '@commander-js/extra-typings'
import Table from 'cli-table3'

import {
	collapseRepeatedListings,
	GOLD_SKIN_PRICE,
	isGoldSkin,
	LEGACY_CLIENT_BUILD,
	listingKind,
	UNLISTED_SKIN_ID_BASE,
	UNLISTED_SKIN_RARITY,
	unlistedSkinListing,
} from '../../../../apps/econ/src/catalog-load'
import { readSkins, readStorefrontPage, SKINS, STORE_DUMP, STOREFRONT_FILE } from './catalog.cmd'

import type { StoreListing } from '../../../../apps/econ/src/catalog-load'

/**
 * Write the 2025 general store the econ worker serves.
 *
 *     runx storefront build
 *
 * Storefront 3 is served from one of two files, picked by the caller's token `rn.ver`:
 *
 *   sf3.json       the 2023 store — what builds up to LEGACY_CLIENT_BUILD are served. FROZEN:
 *                  nothing regenerates it, and it is not touched here.
 *   sf3-2025.json  the 2025 store — what a later build is served. Written here, from the dump
 *                  of the real thing.
 *
 * `sf3-2025.json` is `static/db/Watch_EnumValue_3.json` — storefront 3 as the live game served
 * it in 2026, one page, 3300-odd listings — with three edits, none of which touches an id, an
 * item or a list price, and one addition:
 *
 *   sales      the dump was taken during a store-wide sale (80% off nearly everything, no end
 *              date). The client applies a listing's `StorefrontSaleData` itself and posts the
 *              discounted number as `RequestedPrice`; this server's price check knows only
 *              list prices, so a sale that stays in the file refuses every purchase as "Price
 *              has changed". Every `StorefrontSaleData` is nulled and the `Price` beside it —
 *              the list price — stands.
 *   repeats    twenty listings appear twice, byte for byte. One copy is kept (`findStoreItem`
 *              resolves a purchase by `PurchasableItemId`, and a store showing an item twice is
 *              a dump artifact rather than a merchandising decision) — the catalog load
 *              collapses them the same way, see `collapseRepeatedListings`.
 *   NextUpdate the dump's is the real store's next rotation, already in the past. The client
 *              refetches after it; this file is regenerated by hand, so it carries a far-future
 *              sentinel like every other static storefront here.
 *
 *   skins      the store lists 99 equipment skins; `static/db/skins.json` knows 272, and the
 *              weekly gift pool and the discovery rows draw skins from the store. The ones the
 *              store never listed are appended as listings of their own — rarity 50, priced
 *              from it, numbered from a million — see `unlistedSkinListing`. A skin in both
 *              takes the store's listing: the capture's names and rarities are wrong wherever
 *              the two can be compared.
 *   thumbnails every skin listing — the game's own 99 and the appended ones alike — and every
 *              consumable listing has its `ThumbnailImageName` set to `""`. The dump names a
 *              PNG per item that this server does not have.
 *   gold       a skin whose name carries `(Gold)` sells at `GOLD_SKIN_PRICE`, 1,000,000 tokens,
 *              subscriber price the same: no discount, no sale.
 *   context    a drop whose `Context` is `NO_CONTEXT` (-1) gets 0. The dump carries -1 on
 *              exactly 46 listings — the 22 permanent hair dyes and the 24 dice skins, the
 *              things the live game sells from a surface of its own rather than the store page
 *              — and every other listing says 0 or a positive category. Served with -1 the hair
 *              dyes did not work; swapping those 22 listings for the ones the earlier generated
 *              store carried (Context 0, ids and prices of its own) fixed them, and -1 is the
 *              one member that set the dyes apart from the thousands of listings that work.
 *              See `withStoreContext`.
 *
 * Everything else — `SubscriberDiscountPercent`, `SubscriberPrices`, custom-item listings, the
 * token bundles, the developer-tier items, `AvailableAt` dates — is the store as the game had
 * it. `runx catalog load` reads the file this writes and nothing else, which is what makes a
 * listing's `PurchasableItemId` and a `catalog` row's `catalog_id` one number. The dump itself
 * stays in `static/db` for reference and for the next time a fresher one turns up.
 */

/**
 * Far enough out that the client never refetches — the sentinel every static storefront here
 * carries. A real storefront rotates; this file is regenerated by hand, so it must not expire
 * on its own.
 */
const NEXT_UPDATE = '2226-06-14T00:12:20.1324853Z'

/** Whether a listing is served without its thumbnail: every skin and every consumable. */
export const blanksThumbnail = (listing: StoreListing): boolean =>
	listing.GiftDrop.EquipmentModificationGuid !== '' || listing.GiftDrop.ConsumableItemDesc !== ''

/** The `Context` the dump puts on a drop the store page does not sell: the hair dyes, the dice skins. */
export const NO_CONTEXT = -1

/** The `Context` every ordinary listing carries — what the generated store gave the hair dyes. */
const STORE_CONTEXT = 0

/** Whether a listing's drop carries the dump's out-of-store `Context`. */
export const hasNoContext = (listing: StoreListing): boolean =>
	listing.GiftDrop.Context === NO_CONTEXT

/** The listing with its drop's `Context` brought in from {@link NO_CONTEXT} to the store's. */
export const withStoreContext = (listing: StoreListing): StoreListing => ({
	...listing,
	GiftDrop: { ...listing.GiftDrop, Context: STORE_CONTEXT },
})

/** A price list with its sale removed: the list price, nothing on top. */
const withoutSale = <T extends { StorefrontSaleData: unknown }>(prices: T[] | null): T[] | null =>
	prices === null ? null : prices.map((p) => ({ ...p, StorefrontSaleData: null }))

const build = new Command('build')
	.description('Write sf3-2025.json from the 2025 store dump')
	.action(async () => {
		const [dump, skins] = await Promise.all([readStorefrontPage(STORE_DUMP), readSkins()])

		// One listing per id — the same collapse the catalog load applies, so the file and the
		// table agree on what is a repeat and what is an item.
		const { listings, repeats } = collapseRepeatedListings(dump.StoreItems)

		let sales = 0
		const items = listings.map((listing) => {
			if (listing.Prices.some((p) => p.StorefrontSaleData !== null)) sales++
			return {
				...listing,
				Prices: withoutSale(listing.Prices) ?? [],
				SubscriberPrices: withoutSale(listing.SubscriberPrices),
			}
		})

		// The skins the store never listed, appended in capture order under numbers of their own.
		// A capture guid the store lists is skipped: the listing is the real record. So is a guid
		// the capture repeats.
		const listedSkins = new Set(items.map((i) => i.GiftDrop.EquipmentModificationGuid))
		let added = 0
		for (const skin of skins) {
			if (listedSkins.has(skin.ModificationGuid)) continue
			listedSkins.add(skin.ModificationGuid)
			items.push(unlistedSkinListing(skin, UNLISTED_SKIN_ID_BASE + added++))
		}

		// No skin and no consumable names a thumbnail — the dump's PNGs are not served here.
		let blanked = 0
		for (const item of items) {
			if (!blanksThumbnail(item)) continue
			if (item.GiftDrop.ThumbnailImageName !== '') blanked++
			item.GiftDrop = { ...item.GiftDrop, ThumbnailImageName: '' }
		}

		// Gold skins at their prestige price, in tokens only, no discount.
		let gold = 0
		for (const item of items) {
			if (!isGoldSkin(item)) continue
			gold++
			const priced = { CurrencyType: 2, Price: GOLD_SKIN_PRICE, StorefrontSaleData: null }
			item.Prices = [priced]
			item.SubscriberPrices = [priced]
		}

		// Out-of-store drops brought onto the store page, see `withStoreContext`.
		let recontexted = 0
		for (const [i, item] of items.entries()) {
			if (!hasNoContext(item)) continue
			recontexted++
			items[i] = withStoreContext(item)
		}

		writeFileSync(
			STOREFRONT_FILE,
			`${JSON.stringify({ ...dump, StoreItems: items, NextUpdate: NEXT_UPDATE }, null, '\t')}\n`
		)

		const perKind = new Map<string, number>()
		for (const listing of items) {
			const k = listingKind(listing)
			perKind.set(k, (perKind.get(k) ?? 0) + 1)
		}
		const table = new Table({ head: ['listing', 'count'] })
		for (const [k, n] of [...perKind].sort((a, b) => b[1] - a[1])) table.push([k, String(n)])
		console.log(table.toString())
		const unpriced = items.filter((i) => i.Prices.length === 0).length
		if (unpriced > 0) {
			console.log(chalk.yellow(`${unpriced} listing(s) carry no price and cannot be bought`))
		}
		console.log(
			chalk.green(
				`✓ ${STOREFRONT_FILE}: ${items.length} listings from ${STORE_DUMP} ` +
					`(${repeats} repeated listing(s) dropped, ${sales} sale(s) removed) ` +
					`+ ${added} skin(s) from ${SKINS} at rarity ${UNLISTED_SKIN_RARITY}, ` +
					`${blanked} skin/consumable thumbnail(s) blanked, ${gold} gold skin(s) at ${GOLD_SKIN_PRICE}, ` +
					`${recontexted} drop(s) with Context ${NO_CONTEXT} set to ${STORE_CONTEXT}`
			)
		)
		console.log(
			`  build ${LEGACY_CLIENT_BUILD} and earlier is served the frozen sf3.json; later builds this file`
		)
	})

export const storefrontCmd = new Command('storefront')
	.description('Write the 2025 general store the econ worker serves')
	// Bare `storefront` (no subcommand) prints help and exits cleanly, rather than commander's
	// default "missing command" error (exit 1).
	.action((_opts, command: Command) => command.outputHelp())
	.addCommand(build)
	.addHelpText(
		'after',
		`
Storefront 3 is served from two files by the caller's build: sf3.json (the 2023 store,
frozen) for ${LEGACY_CLIENT_BUILD} and earlier, sf3-2025.json for later builds.

sf3-2025.json is the real 2025 store — ${STORE_DUMP} — with its captured
sale removed, repeated listings collapsed and a far-future NextUpdate, plus the equipment skins
the store never listed (${SKINS}) as rarity-${UNLISTED_SKIN_RARITY} listings numbered from
${UNLISTED_SKIN_ID_BASE}; every skin's and consumable's ThumbnailImageName is ""; a "(Gold)"
skin sells at ${GOLD_SKIN_PRICE} tokens with no discount; a drop with Context ${NO_CONTEXT} (the hair
dyes and the dice skins) is served with Context 0. Ids, items and list prices are otherwise the
dump's. \`runx catalog
load\` reads the file this writes and nothing else, so a listing's PurchasableItemId is its
catalog_id.

Regenerate whenever the dump or the skin capture changes, then reload the catalog.

Examples:
  $ runx storefront build`
	)
